version: '3.8'
services:
  web:
    build: .
    command: python /rental/manage.py runserver 0.0.0.0:8000
    #command: gunicorn rental.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/rental
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=4-7!kh6c^_v5s97aq@_znc&-)hj)x6ji^lx2!tckc+!eqekutu"
      - "DJANGO_DEBUG=True"
      #- "EMAIL_HOST_PASSWORD=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"
      - "CLOUDINARY_URL=cloudinary://397356611417876:nSftT-Z058cktrA2M4pgBfHYybc@hu6y0moa2"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
volumes:
  postgres_data: