# Generated by Django 3.2.10 on 2021-12-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter search tags separated by commas.', max_length=200),
        ),
    ]
