# Generated by Django 3.2.10 on 2021-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_home_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='neighbourhood',
            field=models.CharField(blank=True, help_text='Which community is the home located?', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='rent',
            field=models.IntegerField(blank=True, help_text='Rent amount in $', null=True),
        ),
    ]
