# Generated by Django 3.2.9 on 2021-12-05 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_auto_20211204_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Postal Code must be 7 characters.')]),
        ),
    ]
