# Generated by Django 3.2.9 on 2021-12-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0003_alter_home_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.locationprovince'),
        ),
    ]
