# Generated by Django 3.2.9 on 2021-12-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0004_alter_home_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['date_added'], 'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
    ]
