# Generated by Django 3.2.10 on 2021-12-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0004_auto_20211213_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='homephotos',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hometype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='locationcity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='locationprovince',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
